#!/bin/sh -x
pyuic5 mainwin.ui  > Df_UiMainwin.py
#pyuic5 dialog.ui  > Df_UiDialog.py
pyuic5 config.ui  > Df_UiConfig.py
#pyuic5 preview.ui  > Df_UiPreview.py
pyuic5 jobstatus.ui  > Df_UiJobstatus.py
pyuic5 help.ui  > Df_UiHelp.py
pyuic5 find.ui  > Df_UiFind.py
#pyside-rcc dragonfly.qrc  > dragonfly_rc.py

mkdir -p openwith/build
cd openwith/build
cmake ..
make
mv openwith ..
