#!/bin/sh -x
pyuic5 mainwin.ui  > Df_UiMainwin.py
#pyuic5 dialog.ui  > Df_UiDialog.py
pyuic5 config.ui  > Df_UiConfig.py
#pyuic5 preview.ui  > Df_UiPreview.py
pyuic5 jobstatus.ui  > Df_UiJobstatus.py
pyuic5 help.ui  > Df_UiHelp.py
pyuic5 find.ui  > Df_UiFind.py
#pyside-rcc dragonfly.qrc  > dragonfly_rc.py

mkdir -p openwith/build
cd openwith/build
cmake ..
make
mv openwith ..
cd ../..

V=dragonfly_21.0-1_amd64

# Build .deb Debian package
R=rel/$V
A=$R/usr/share/dragonfly
rm -rf rel
mkdir -p $R/usr/bin $R/DEBIAN $A $A/openwith $R/usr/share/applications
cp dragonfly.desktop $R/usr/share/applications
ln -s /usr/share/dragonfly/dragonfly $R/usr/bin
cp control $R/DEBIAN
cp -r 3pp vfs icons dragonfly *.py helptext.html setup dragonfly.desktop dragonfly.desktop.home ../LICENSE ../README $A
cp openwith/openwith $A/openwith
dpkg-deb --build --root-owner-group $R

# Build the tarball
cd rel/$V/usr/share
tar czf ../../../$V.tar.gz dragonfly
