#!/bin/sh -x
#VERSION=`date +"%Y%m%d.%H%M%S-git"`
VERSION=`cat version`
if [ "$1" = "arch" ]
then
    echo arch
    # TODO: This code needs to change when/if dragonfly navigator is not built from git in AUR. Currently, it is always from git.
    VERSION=`printf "r%s.%s" "$(git rev-list --count HEAD)" "$(git rev-parse --short HEAD)"`
fi

V=dragonfly_$VERSION-1_amd64
sed "s/VERSION/$VERSION/g" < control.pre > control
sed "s/VERSION/$VERSION/g" < helptext.html.pre > helptext.html

pyuic6 mainwin.ui  > Df_UiMainwin.py
#pyuic6 dialog.ui  > Df_UiDialog.py
pyuic6 config.ui  > Df_UiConfig.py
#pyuic6 preview.ui  > Df_UiPreview.py
pyuic6 jobstatus.ui  > Df_UiJobstatus.py
pyuic6 help.ui  > Df_UiHelp.py
pyuic6 find.ui  > Df_UiFind.py
#pyside-rcc dragonfly.qrc  > dragonfly_rc.py

if [ "$1" = "arch" ]
then
    echo arch
    # Packaging for Arch Linux
    R=$DESTDIR
    A=$R/usr/share/dragonfly
    mkdir -p $R/usr/bin $A $A/openwith $R/usr/share/applications
    cp dragonfly.desktop $R/usr/share/applications
    ln -s /usr/share/dragonfly/dragonfly $R/usr/bin
    #pandoc --to=plain ../README.md > $A/README
    cp -r 3pp vfs icons dragonfly *.py helptext.html setup dragonfly.desktop dragonfly.desktop.home ../LICENSE terminal $A
    cp openwith/openwith openwith/openwith.qt openwith/openwith.gtk $A/openwith
    exit 0
fi

TD="$PWD"
cd "$TD"/openwith/qt
rm -rf build; mkdir build; cd build; cmake -DQT_MAJOR_VERSION=6 ..; make
mv openwith "$TD"/openwith/openwith.qt
cd "$TD"/openwith/gtk
rm -rf build; mkdir build; cd build; cmake ..; make
mv gtk-open-with "$TD"/openwith/openwith.gtk
cd "$TD"

# Build .deb Debian package
R=rel/$V
A=$R/usr/share/dragonfly
rm -rf rel
mkdir -p $R/usr/bin $R/DEBIAN $A $A/openwith $R/usr/share/applications
cp dragonfly.desktop $R/usr/share/applications
ln -s /usr/share/dragonfly/dragonfly $R/usr/bin
cp control $R/DEBIAN
#pandoc --to=plain ../README.md > $A/README
cp -r 3pp vfs icons dragonfly *.py helptext.html setup dragonfly.desktop dragonfly.desktop.home ../LICENSE terminal $A
cp openwith/openwith openwith/openwith.qt openwith/openwith.gtk $A/openwith
dpkg-deb --build --root-owner-group $R

# Build the tarball
cd rel/$V/usr/share
tar czf ../../../$V.tar.gz dragonfly
