#!/bin/sh
#export PATH=/cygdrive/c/python27/scripts:$PATH
pyside-uic mainwin.ui  > Df_UiMainwin.py
pyside-uic dialog.ui  > Df_UiDialog.py
pyside-uic config.ui  > Df_UiConfig.py
pyside-uic preview.ui  > Df_UiPreview.py
pyside-uic jobstatus.ui  > Df_UiJobstatus.py
pyside-uic help.ui  > Df_UiHelp.py
pyside-uic find.ui  > Df_UiFind.py
pyside-rcc dragonfly.qrc  > dragonfly_rc.py

