#!/bin/sh -x
SRC=/cygdrive/c/users/hch/git/ws/src
cd $SRC
c:/python27/python -O -m compileall .
cd /cygdrive/c/users/hch/build
#rm -rf DragonflyNavigator
mkdir -p DragonflyNavigator
cd DragonflyNavigator
mkdir -p src/icons
cd src
cp $SRC/icons/dragonfly.png icons
cp $SRC/icons/Letters.png icons
cp -r $SRC/res .
mkdir -p cygwin/bin
cp /bin/cp /bin/mv /bin/rm /bin/*dll cygwin/bin
cp $SRC/*pyo .
mkdir -p vfs
cp $SRC/vfs/*pyo vfs
cp $SRC/dragonfly.bat ..
#cp -r c:/python27 ../python
exit 0

/cygdrive/c/Python27/python.exe pyinstaller.py -y -n DragonflyNavigator 'c:\Users\hch\git\ws\src\Df_Main.py'
cd /cygdrive/c/pyinstaller/DragonflyNavigator/dist/DragonflyNavigator
mkdir -p src/icons
cp /cygdrive/c/Users/hch/git/ws/src/icons/dragonfly.png src/icons
cp /cygdrive/c/Users/hch/git/ws/src/icons/Letters.png src/icons
cp -r /cygdrive/c/Users/hch/git/ws/src/res src
mkdir -p cygwin/bin
cp /bin/cp /bin/mv /bin/rm /bin/*dll cygwin/bin
