# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'config.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Config(object):
    def setupUi(self, Config):
        Config.setObjectName("Config")
        Config.resize(624, 398)
        self.gridLayout = QtWidgets.QGridLayout(Config)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox = QtWidgets.QGroupBox(Config)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.rememberStartFolders = QtWidgets.QRadioButton(self.groupBox)
        self.rememberStartFolders.setChecked(True)
        self.rememberStartFolders.setObjectName("rememberStartFolders")
        self.gridLayout_2.addWidget(self.rememberStartFolders, 0, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 3, 0, 1, 1)
        self.leftStartDir = QtWidgets.QLineEdit(self.groupBox)
        self.leftStartDir.setObjectName("leftStartDir")
        self.gridLayout_2.addWidget(self.leftStartDir, 4, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 5, 0, 1, 1)
        self.rightStartDir = QtWidgets.QLineEdit(self.groupBox)
        self.rightStartDir.setObjectName("rightStartDir")
        self.gridLayout_2.addWidget(self.rightStartDir, 6, 0, 1, 1)
        self.startAtSpecifiedFolders = QtWidgets.QRadioButton(self.groupBox)
        self.startAtSpecifiedFolders.setObjectName("startAtSpecifiedFolders")
        self.gridLayout_2.addWidget(self.startAtSpecifiedFolders, 1, 0, 1, 1)
        self.useCurrentLeft = QtWidgets.QPushButton(self.groupBox)
        self.useCurrentLeft.setObjectName("useCurrentLeft")
        self.gridLayout_2.addWidget(self.useCurrentLeft, 4, 1, 1, 1)
        self.useCurrentRight = QtWidgets.QPushButton(self.groupBox)
        self.useCurrentRight.setObjectName("useCurrentRight")
        self.gridLayout_2.addWidget(self.useCurrentRight, 6, 1, 1, 1)
        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(Config)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 3, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(Config)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.showHidden = QtWidgets.QCheckBox(self.groupBox_2)
        self.showHidden.setTristate(False)
        self.showHidden.setObjectName("showHidden")
        self.gridLayout_3.addWidget(self.showHidden, 0, 0, 1, 1)
        self.confirmDelete = QtWidgets.QCheckBox(self.groupBox_2)
        self.confirmDelete.setObjectName("confirmDelete")
        self.gridLayout_3.addWidget(self.confirmDelete, 2, 0, 1, 1)
        self.showThumbs = QtWidgets.QCheckBox(self.groupBox_2)
        self.showThumbs.setChecked(True)
        self.showThumbs.setTristate(False)
        self.showThumbs.setObjectName("showThumbs")
        self.gridLayout_3.addWidget(self.showThumbs, 1, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox_2, 1, 0, 1, 1)

        self.retranslateUi(Config)
        self.buttonBox.accepted.connect(Config.accept)
        self.buttonBox.rejected.connect(Config.reject)
        QtCore.QMetaObject.connectSlotsByName(Config)

    def retranslateUi(self, Config):
        _translate = QtCore.QCoreApplication.translate
        Config.setWindowTitle(_translate("Config", "Configuration"))
        self.groupBox.setTitle(_translate("Config", "Start directories"))
        self.rememberStartFolders.setText(_translate("Config", "Remember start directories from last run"))
        self.label.setText(_translate("Config", "Left start directory"))
        self.label_2.setText(_translate("Config", "Right start directory"))
        self.startAtSpecifiedFolders.setText(_translate("Config", "Always start at specified directories"))
        self.useCurrentLeft.setText(_translate("Config", "Use current"))
        self.useCurrentRight.setText(_translate("Config", "Use current"))
        self.groupBox_2.setTitle(_translate("Config", "Miscellaneous"))
        self.showHidden.setText(_translate("Config", "Show hidden files"))
        self.confirmDelete.setText(_translate("Config", "Confirm delete"))
        self.showThumbs.setText(_translate("Config", "Show photo thumbnails (may slow down listing of directories)"))
