# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwin.ui'
#
# Created: Wed Feb 29 18:39:38 2012
#      by: pyside-uic 0.2.13 running on PySide 1.1.0
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(650, 544)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.splitter = QtGui.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.layoutWidget = QtGui.QWidget(self.splitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.mainHoriz = QtGui.QHBoxLayout(self.layoutWidget)
        self.mainHoriz.setContentsMargins(0, 0, 0, 0)
        self.mainHoriz.setObjectName("mainHoriz")
        self.left = QtGui.QGridLayout()
        self.left.setObjectName("left")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.left_up = QtGui.QPushButton(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.left_up.sizePolicy().hasHeightForWidth())
        self.left_up.setSizePolicy(sizePolicy)
        self.left_up.setText("")
        self.left_up.setObjectName("left_up")
        self.horizontalLayout.addWidget(self.left_up)
        self.left_history = QtGui.QPushButton(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.left_history.sizePolicy().hasHeightForWidth())
        self.left_history.setSizePolicy(sizePolicy)
        self.left_history.setObjectName("left_history")
        self.horizontalLayout.addWidget(self.left_history)
        self.left_bookmarks = QtGui.QPushButton(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.left_bookmarks.sizePolicy().hasHeightForWidth())
        self.left_bookmarks.setSizePolicy(sizePolicy)
        self.left_bookmarks.setObjectName("left_bookmarks")
        self.horizontalLayout.addWidget(self.left_bookmarks)
        self.left.addLayout(self.horizontalLayout, 4, 0, 1, 2)
        self.left_status = QtGui.QLabel(self.layoutWidget)
        self.left_status.setAlignment(QtCore.Qt.AlignCenter)
        self.left_status.setObjectName("left_status")
        self.left.addWidget(self.left_status, 2, 0, 1, 2)
        self.left_tree = QtGui.QTreeWidget(self.layoutWidget)
        self.left_tree.setRootIsDecorated(False)
        self.left_tree.setObjectName("left_tree")
        self.left_tree.headerItem().setText(0, "1")
        self.left.addWidget(self.left_tree, 6, 0, 1, 1)
        self.left_path = QtGui.QLineEdit(self.layoutWidget)
        self.left_path.setObjectName("left_path")
        self.left.addWidget(self.left_path, 5, 0, 1, 1)
        self.mainHoriz.addLayout(self.left)
        self.center = QtGui.QVBoxLayout()
        self.center.setObjectName("center")
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.configure = QtGui.QPushButton(self.layoutWidget)
        self.configure.setObjectName("configure")
        self.verticalLayout_4.addWidget(self.configure)
        self.help = QtGui.QPushButton(self.layoutWidget)
        self.help.setObjectName("help")
        self.verticalLayout_4.addWidget(self.help)
        self.center.addLayout(self.verticalLayout_4)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.toleft = QtGui.QToolButton(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toleft.sizePolicy().hasHeightForWidth())
        self.toleft.setSizePolicy(sizePolicy)
        self.toleft.setText("")
        self.toleft.setObjectName("toleft")
        self.horizontalLayout_5.addWidget(self.toleft)
        self.toright = QtGui.QToolButton(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toright.sizePolicy().hasHeightForWidth())
        self.toright.setSizePolicy(sizePolicy)
        self.toright.setText("")
        self.toright.setObjectName("toright")
        self.horizontalLayout_5.addWidget(self.toright)
        self.center.addLayout(self.horizontalLayout_5)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.center.addItem(spacerItem)
        self.actionButtonsLayout = QtGui.QVBoxLayout()
        self.actionButtonsLayout.setObjectName("actionButtonsLayout")
        self.center.addLayout(self.actionButtonsLayout)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.center.addItem(spacerItem1)
        self.mainHoriz.addLayout(self.center)
        self.right = QtGui.QGridLayout()
        self.right.setObjectName("right")
        self.right_status = QtGui.QLabel(self.layoutWidget)
        self.right_status.setAlignment(QtCore.Qt.AlignCenter)
        self.right_status.setObjectName("right_status")
        self.right.addWidget(self.right_status, 2, 0, 1, 2)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.right_up = QtGui.QPushButton(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.right_up.sizePolicy().hasHeightForWidth())
        self.right_up.setSizePolicy(sizePolicy)
        self.right_up.setText("")
        self.right_up.setObjectName("right_up")
        self.horizontalLayout_4.addWidget(self.right_up)
        self.right_history = QtGui.QPushButton(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.right_history.sizePolicy().hasHeightForWidth())
        self.right_history.setSizePolicy(sizePolicy)
        self.right_history.setObjectName("right_history")
        self.horizontalLayout_4.addWidget(self.right_history)
        self.right_bookmarks = QtGui.QPushButton(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.right_bookmarks.sizePolicy().hasHeightForWidth())
        self.right_bookmarks.setSizePolicy(sizePolicy)
        self.right_bookmarks.setObjectName("right_bookmarks")
        self.horizontalLayout_4.addWidget(self.right_bookmarks)
        self.right.addLayout(self.horizontalLayout_4, 4, 0, 1, 2)
        self.right_tree = QtGui.QTreeWidget(self.layoutWidget)
        self.right_tree.setRootIsDecorated(False)
        self.right_tree.setObjectName("right_tree")
        self.right_tree.headerItem().setText(0, "1")
        self.right.addWidget(self.right_tree, 6, 0, 1, 1)
        self.right_path = QtGui.QLineEdit(self.layoutWidget)
        self.right_path.setObjectName("right_path")
        self.right.addWidget(self.right_path, 5, 0, 1, 1)
        self.mainHoriz.addLayout(self.right)
        self.jobs = QtGui.QTreeWidget(self.splitter)
        self.jobs.setRootIsDecorated(False)
        self.jobs.setObjectName("jobs")
        self.jobs.headerItem().setText(0, "1")
        self.gridLayout.addWidget(self.splitter, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Dragonfly Navigator", None, QtGui.QApplication.UnicodeUTF8))
        self.left_history.setText(QtGui.QApplication.translate("MainWindow", "History", None, QtGui.QApplication.UnicodeUTF8))
        self.left_bookmarks.setText(QtGui.QApplication.translate("MainWindow", "Bookmarks", None, QtGui.QApplication.UnicodeUTF8))
        self.left_status.setText(QtGui.QApplication.translate("MainWindow", "status", None, QtGui.QApplication.UnicodeUTF8))
        self.configure.setText(QtGui.QApplication.translate("MainWindow", "Configure", None, QtGui.QApplication.UnicodeUTF8))
        self.help.setText(QtGui.QApplication.translate("MainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.right_status.setText(QtGui.QApplication.translate("MainWindow", "status", None, QtGui.QApplication.UnicodeUTF8))
        self.right_history.setText(QtGui.QApplication.translate("MainWindow", "History", None, QtGui.QApplication.UnicodeUTF8))
        self.right_bookmarks.setText(QtGui.QApplication.translate("MainWindow", "Bookmarks", None, QtGui.QApplication.UnicodeUTF8))

import dragonfly_rc
