# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'config.ui'
#
# Created: Thu Oct 25 20:16:35 2012
#      by: pyside-uic 0.2.14 running on PySide 1.1.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Config(object):
    def setupUi(self, Config):
        Config.setObjectName("Config")
        Config.resize(624, 515)
        self.gridLayout = QtGui.QGridLayout(Config)
        self.gridLayout.setObjectName("gridLayout")
        self.buttonBox = QtGui.QDialogButtonBox(Config)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 4, 0, 1, 1)
        self.groupBox_2 = QtGui.QGroupBox(Config)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.showHidden = QtGui.QCheckBox(self.groupBox_2)
        self.showHidden.setTristate(False)
        self.showHidden.setObjectName("showHidden")
        self.gridLayout_3.addWidget(self.showHidden, 0, 0, 1, 1)
        self.showThumbs = QtGui.QCheckBox(self.groupBox_2)
        self.showThumbs.setChecked(True)
        self.showThumbs.setTristate(False)
        self.showThumbs.setObjectName("showThumbs")
        self.gridLayout_3.addWidget(self.showThumbs, 1, 0, 1, 1)
        self.showIcons = QtGui.QCheckBox(self.groupBox_2)
        self.showIcons.setObjectName("showIcons")
        self.gridLayout_3.addWidget(self.showIcons, 2, 0, 1, 1)
        self.useInternalFileCopy = QtGui.QCheckBox(self.groupBox_2)
        self.useInternalFileCopy.setObjectName("useInternalFileCopy")
        self.gridLayout_3.addWidget(self.useInternalFileCopy, 3, 0, 1, 1)
        self.confirmDelete = QtGui.QCheckBox(self.groupBox_2)
        self.confirmDelete.setObjectName("confirmDelete")
        self.gridLayout_3.addWidget(self.confirmDelete, 4, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox_2, 2, 0, 1, 1)
        self.groupBox = QtGui.QGroupBox(Config)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.rememberStartFolders = QtGui.QRadioButton(self.groupBox)
        self.rememberStartFolders.setChecked(True)
        self.rememberStartFolders.setObjectName("rememberStartFolders")
        self.gridLayout_2.addWidget(self.rememberStartFolders, 0, 0, 1, 1)
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 3, 0, 1, 1)
        self.leftStartDir = QtGui.QLineEdit(self.groupBox)
        self.leftStartDir.setObjectName("leftStartDir")
        self.gridLayout_2.addWidget(self.leftStartDir, 4, 0, 1, 1)
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 5, 0, 1, 1)
        self.rightStartDir = QtGui.QLineEdit(self.groupBox)
        self.rightStartDir.setObjectName("rightStartDir")
        self.gridLayout_2.addWidget(self.rightStartDir, 6, 0, 1, 1)
        self.startAtSpecifiedFolders = QtGui.QRadioButton(self.groupBox)
        self.startAtSpecifiedFolders.setObjectName("startAtSpecifiedFolders")
        self.gridLayout_2.addWidget(self.startAtSpecifiedFolders, 1, 0, 1, 1)
        self.useCurrentLeft = QtGui.QPushButton(self.groupBox)
        self.useCurrentLeft.setObjectName("useCurrentLeft")
        self.gridLayout_2.addWidget(self.useCurrentLeft, 4, 1, 1, 1)
        self.useCurrentRight = QtGui.QPushButton(self.groupBox)
        self.useCurrentRight.setObjectName("useCurrentRight")
        self.gridLayout_2.addWidget(self.useCurrentRight, 6, 1, 1, 1)
        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 1)
        self.groupBox_3 = QtGui.QGroupBox(Config)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_4 = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_3 = QtGui.QLabel(self.groupBox_3)
        self.label_3.setObjectName("label_3")
        self.gridLayout_4.addWidget(self.label_3, 4, 0, 1, 1)
        self.date_ddmmyy = QtGui.QRadioButton(self.groupBox_3)
        self.date_ddmmyy.setObjectName("date_ddmmyy")
        self.gridLayout_4.addWidget(self.date_ddmmyy, 7, 1, 1, 1)
        self.date_mmddyy = QtGui.QRadioButton(self.groupBox_3)
        self.date_mmddyy.setObjectName("date_mmddyy")
        self.gridLayout_4.addWidget(self.date_mmddyy, 5, 1, 1, 1)
        self.time12h = QtGui.QCheckBox(self.groupBox_3)
        self.time12h.setObjectName("time12h")
        self.gridLayout_4.addWidget(self.time12h, 2, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.groupBox_3)
        self.label_4.setObjectName("label_4")
        self.gridLayout_4.addWidget(self.label_4, 2, 0, 1, 1)
        self.date_yymmdd = QtGui.QRadioButton(self.groupBox_3)
        self.date_yymmdd.setObjectName("date_yymmdd")
        self.gridLayout_4.addWidget(self.date_yymmdd, 4, 1, 1, 1)
        self.date_sep = QtGui.QLineEdit(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.date_sep.sizePolicy().hasHeightForWidth())
        self.date_sep.setSizePolicy(sizePolicy)
        self.date_sep.setMinimumSize(QtCore.QSize(1, 0))
        self.date_sep.setObjectName("date_sep")
        self.gridLayout_4.addWidget(self.date_sep, 11, 1, 1, 1)
        self.label_5 = QtGui.QLabel(self.groupBox_3)
        self.label_5.setObjectName("label_5")
        self.gridLayout_4.addWidget(self.label_5, 11, 0, 1, 1)
        self.label_6 = QtGui.QLabel(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setObjectName("label_6")
        self.gridLayout_4.addWidget(self.label_6, 5, 2, 1, 1)
        self.gridLayout.addWidget(self.groupBox_3, 1, 0, 1, 1)

        self.retranslateUi(Config)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), Config.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), Config.reject)
        QtCore.QMetaObject.connectSlotsByName(Config)

    def retranslateUi(self, Config):
        Config.setWindowTitle(QtGui.QApplication.translate("Config", "Configuration", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("Config", "Miscellaneous", None, QtGui.QApplication.UnicodeUTF8))
        self.showHidden.setText(QtGui.QApplication.translate("Config", "Show hidden files", None, QtGui.QApplication.UnicodeUTF8))
        self.showThumbs.setText(QtGui.QApplication.translate("Config", "Show photo thumbnails (may slow down listing of folders)", None, QtGui.QApplication.UnicodeUTF8))
        self.showIcons.setText(QtGui.QApplication.translate("Config", "Show file icons (may slow down listing of folders)", None, QtGui.QApplication.UnicodeUTF8))
        self.useInternalFileCopy.setText(QtGui.QApplication.translate("Config", "Use internal method for copying files (faster but shows no progress bar)", None, QtGui.QApplication.UnicodeUTF8))
        self.confirmDelete.setText(QtGui.QApplication.translate("Config", "Confirm delete", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("Config", "Start directories", None, QtGui.QApplication.UnicodeUTF8))
        self.rememberStartFolders.setText(QtGui.QApplication.translate("Config", "Remember start directories from last run", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Config", "Left start folder", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Config", "Right start folder", None, QtGui.QApplication.UnicodeUTF8))
        self.startAtSpecifiedFolders.setText(QtGui.QApplication.translate("Config", "Always start at specified directories", None, QtGui.QApplication.UnicodeUTF8))
        self.useCurrentLeft.setText(QtGui.QApplication.translate("Config", "Use current", None, QtGui.QApplication.UnicodeUTF8))
        self.useCurrentRight.setText(QtGui.QApplication.translate("Config", "Use current", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("Config", "Formats", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Config", "Date format", None, QtGui.QApplication.UnicodeUTF8))
        self.date_ddmmyy.setText(QtGui.QApplication.translate("Config", "DD/MM/YY", None, QtGui.QApplication.UnicodeUTF8))
        self.date_mmddyy.setText(QtGui.QApplication.translate("Config", "MM/DD/YY", None, QtGui.QApplication.UnicodeUTF8))
        self.time12h.setText(QtGui.QApplication.translate("Config", "12h time (AM/PM)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Config", "Time format", None, QtGui.QApplication.UnicodeUTF8))
        self.date_yymmdd.setText(QtGui.QApplication.translate("Config", "YY-MM-DD", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Config", "Date separator", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Config", " ", None, QtGui.QApplication.UnicodeUTF8))

