#!/bin/sh
#cd style
# styles plastique "default" motif gtk cleanlooks
python Df_Main.py 2>&1 | grep -v "Unable to retrieve Watch object"
#-style cleanlooks 
#-stylesheet dragonfly.qss


#python Df_Main.py -style plastique
#pyside-uic mainwin.ui  > apa.py ; python pysidetest2.py -style qmc2-black-0.10.qss

