#!/bin/sh

# Use qt6ct to modify appearance of dragonfly navigator if needed. The below code is a bit too heavy handed.
#if [ "$XDG_CURRENT_DESKTOP" != "KDE" ]; then
#  export QT_STYLE_OVERRIDE=Breeze
#  #export QT_QPA_PLATFORMTHEME=gnome
#fi

if [ ! -z "$1" ]; then 
  L=`readlink -f $1`
fi
if [ ! -z "$2" ]; then 
  R=`readlink -f $2`
fi
D=`readlink -f $0`
cd `dirname $D`
export RELEASE=True
exec python3 -E Df_Main.py "$L" "$R" 1>&2
#exec -a dragonfly python3 -E Df_Main.py -name "Dragonfly Navigator" "$L" "$R" 1>&2
#exec -a dragonfly ./Df_Main.py "$L" "$R" 1>&2
#python -m cProfile -s time Df_Main.py 2>&1

