#!/bin/sh -x

if [ "$1" = "arch" ]
then
    echo "Creating package for Arch Linux"
    R=$DESTDIR
    A=$R/usr/share/dragonfly
    mkdir -p $R/usr/bin $A $A/openwith $R/usr/share/applications
    cp dragonfly.desktop $R/usr/share/applications
    ln -s /usr/share/dragonfly/dragonfly $R/usr/bin
    #pandoc --to=plain ../README.md > $A/README
    cp -r 3pp vfs icons dragonfly *.py helptext.html setup dragonfly.desktop dragonfly.desktop.home ../LICENSE terminal $A
    cp openwith/openwith openwith/openwith.qt openwith/openwith.gtk $A/openwith
    exit 0
fi

